In [294]:
# Multilabel Classification problem of Blog Authorship Corpus using NLP

In [2]:
# 1) Read the dataset
import pandas as pd

a=pd.read_csv('blogtext.csv')
a.head(10)

,id,gender,age,topic,sign,date,text
0,2059027,male,15,Student,Leo,"14,May,2004","Info has been found (+/- 100 pages,..."
1,2059027,male,15,Student,Leo,"13,May,2004",These are the team members: Drewe...
2,2059027,male,15,Student,Leo,"12,May,2004",In het kader van kernfusie op aarde...
3,2059027,male,15,Student,Leo,"12,May,2004",testing!!! testing!!!
4,3581210,male,33,InvestmentBanking,Aquarius,"11,June,2004",Thanks to Yahoo!'s Toolbar I can ...
5,3581210,male,33,InvestmentBanking,Aquarius,"10,June,2004",I had an interesting conversation...
6,3581210,male,33,InvestmentBanking,Aquarius,"10,June,2004",Somehow Coca-Cola has a way of su...
7,3581210,male,33,InvestmentBanking,Aquarius,"10,June,2004","If anything, Korea is a country o..."
8,3581210,male,33,InvestmentBanking,Aquarius,"10,June,2004",Take a read of this news article ...
9,3581210,male,33,InvestmentBanking,Aquarius,"09,June,2004",I surf the English news sites a l...

In [3]:
# Dataset details

a.shape

# Over 681284 rows, 7 columns

(681284, 7)

In [66]:
# Considering fewer rows from the dataset for initial analysis

# Read the dataset

df=pd.read_csv('blogtext.csv', nrows=5000)
df

,id,gender,age,topic,sign,date,text
0,2059027,male,15,Student,Leo,"14,May,2004","Info has been found (+/- 100 pages,..."
1,2059027,male,15,Student,Leo,"13,May,2004",These are the team members: Drewe...
2,2059027,male,15,Student,Leo,"12,May,2004",In het kader van kernfusie op aarde...
3,2059027,male,15,Student,Leo,"12,May,2004",testing!!! testing!!!
4,3581210,male,33,InvestmentBanking,Aquarius,"11,June,2004",Thanks to Yahoo!'s Toolbar I can ...
5,3581210,male,33,InvestmentBanking,Aquarius,"10,June,2004",I had an interesting conversation...
6,3581210,male,33,InvestmentBanking,Aquarius,"10,June,2004",Somehow Coca-Cola has a way of su...
7,3581210,male,33,InvestmentBanking,Aquarius,"10,June,2004","If anything, Korea is a country o..."
8,3581210,male,33,InvestmentBanking,Aquarius,"10,June,2004",Take a read of this news article ...
9,3581210,male,33,InvestmentBanking,Aquarius,"09,June,2004",I surf the English news sites a l...
10,3581210,male,33,InvestmentBanking,Aquarius,"09,June,2004","Ah, the Korean language...it look..."
11,3581210,male,33,InvestmentBanking,Aquarius,"09,June,2004",If you click on my profile you'll...
12,3581210,male,33,InvestmentBanking,Aquarius,"09,June,2004",Last night was pretty fun...mostl...
13,3581210,male,33,InvestmentBanking,Aquarius,"09,June,2004",There is so much that is differen...
14,3581210,male,33,InvestmentBanking,Aquarius,"09,June,2004","urlLink Here it is, the super..."
15,3581210,male,33,InvestmentBanking,Aquarius,"09,June,2004",One thing I love about Seoul (and...
16,3581210,male,33,InvestmentBanking,Aquarius,"09,June,2004",urlLink Wonderful oh-gyup-sal...
17,3581210,male,33,InvestmentBanking,Aquarius,"18,June,2004",Here is the latest from the Korea...
18,3581210,male,33,InvestmentBanking,Aquarius,"17,June,2004","Well, I stand corrected, again. ..."
19,3581210,male,33,InvestmentBanking,Aquarius,"16,June,2004",So I've been in Vancouver a few d...
20,3581210,male,33,InvestmentBanking,Aquarius,"15,June,2004",Whenever I see a pregnant Korean ...
21,3581210,male,33,InvestmentBanking,Aquarius,"14,June,2004",My wife posed a strange question ...
22,3581210,male,33,InvestmentBanking,Aquarius,"13,June,2004","As readers will know, my favorite..."
23,3581210,male,33,InvestmentBanking,Aquarius,"23,June,2004",When I was in Seoul these last fe...
24,3581210,male,33,InvestmentBanking,Aquarius,"22,June,2004",You may have noticed a new featur...
25,3581210,male,33,InvestmentBanking,Aquarius,"20,June,2004","Korea, especially Seoul, is prett..."
26,3581210,male,33,InvestmentBanking,Aquarius,"02,July,2004",It seems everything is not all th...
27,3581210,male,33,InvestmentBanking,Aquarius,"01,July,2004",This may be a long blog...got a l...
28,3581210,male,33,InvestmentBanking,Aquarius,"01,July,2004",I've always thought of Seoul's u...
29,3581210,male,33,InvestmentBanking,Aquarius,"30,June,2004",Big cities are famous for being e...
...,...,...,...,...,...,...,...
4970,1103575,female,17,indUnk,Scorpio,"06,July,2003",mm... I was going to rant about time/c...
4971,1103575,female,17,indUnk,Scorpio,"06,July,2003","So, I guess its kind of like this... I ..."
4972,1103575,female,17,indUnk,Scorpio,"03,July,2003",this shade of red looks more and more l...
4973,1103575,female,17,indUnk,Scorpio,"03,July,2003",...look at me... teaching myself html.....
4974,1103575,female,17,indUnk,Scorpio,"03,July,2003","My name is Rachel. {duh, we already kn..."
4975,1103575,female,17,indUnk,Scorpio,"02,July,2003",Another depressing song... I don't know...
4976,1103575,female,17,indUnk,Scorpio,"01,July,2003",I've been falling to pieces for the pas...
4977,1103575,female,17,indUnk,Scorpio,"31,August,2003",I'm suffocating. My lungs are bursting....
4978,1103575,female,17,indUnk,Scorpio,"30,August,2003",peaches are the nectar of the gods. mm...
4979,1103575,female,17,indUnk,Scorpio,"30,August,2003",AHHH. I need a pillow to scream into. o...
4980,1103575,female,17,indUnk,Scorpio,"29,August,2003",Young. Really young. I'd say anywhe...
4981,1103575,female,17,indUnk,Scorpio,"29,August,2003",that's Sama...
4982,1103575,female,17,indUnk,Scorpio,"29,August,2003",
4983,1103575,female,17,indUnk,Scorpio,"29,August,2003",
4984,1103575,female,17,indUnk,Scorpio,"29,August,2003",this one looks kinda cool squished li...
4985,1103575,female,17,indUnk,Scorpio,"29,August,2003",yay for uploading my pics on to angel...
4986,1103575,female,17,indUnk,Scorpio,"29,August,2003","Ok, so this is the last time today, I p..."
4987,1103575,female,17,indUnk,Scorpio,"28,August,2003","oh, and I forgot... last night at cant..."
4988,1103575,female,17,indUnk,Scorpio,"28,August,2003","So, I got a new commenting host... I di..."
4989,1103575,female,17,indUnk,Scorpio,"28,August,2003",Last night was NOT a good night. {end o...
4990,1103575,female,17,indUnk,Scorpio,"28,August,2003","Sometimes, I swear this song is about m..."
4991,1103575,female,17,indUnk,Scorpio,"28,August,2003",so much for sleeping... I know what ti...
4992,1103575,female,17,indUnk,Scorpio,"28,August,2003",I am: a miserable failure incredibly ir...
4993,1103575,female,17,indUnk,Scorpio,"27,August,2003",hey I've had almost 300 hits... WHO ARE...
4994,1103575,female,17,indUnk,Scorpio,"27,August,2003",This is that Sylvia Plath poem I was ta...
4995,1103575,female,17,indUnk,Scorpio,"27,August,2003",So... I had another one of those dreams...
4996,1103575,female,17,indUnk,Scorpio,"27,August,2003",mmm... strawberry tea for breakfast. To...
4997,1103575,female,17,indUnk,Scorpio,"27,August,2003","Yay for a new layout!! Yeah, I know, I..."
4998,1103575,female,17,indUnk,Scorpio,"26,August,2003","Ok, so I lied... Fed up isn't playing F..."
4999,1103575,female,17,indUnk,Scorpio,"26,August,2003","well, today I went to church and talked..."

In [67]:
# 2) Preprocessing on the Text column
import nltk 
import string 
import re 
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize

# Remove punctutations

df['text'] = df['text'].str.replace( '[^\w\s]' , '' )

In [68]:
# Remove unwanted whitespaces
df['text'] = df['text'].str.strip()

In [69]:
# Convert to Lowercase
df['text'] = df['text'].apply( lambda i : ' '.join( word.lower() for word in i.split()))

In [70]:
# Remove stop words

stop = stopwords.words('english')
df['text'] = df['text'].apply( lambda t : " ".join( word for word in t.split() 
                                                       if word not in stop ) )

In [71]:
# Remove numeric

df['text'] = df['text'].apply( lambda t : re.sub(r'\d+', '', t))

In [72]:
df['text'][0]

'info found  pages  mb pdf files wait untill team leader processed learns html'

In [73]:
df

,id,gender,age,topic,sign,date,text
0,2059027,male,15,Student,Leo,"14,May,2004",info found pages mb pdf files wait untill te...
1,2059027,male,15,Student,Leo,"13,May,2004",team members drewes van der laag urllink mail ...
2,2059027,male,15,Student,Leo,"12,May,2004",het kader van kernfusie op aarde maak je eigen...
3,2059027,male,15,Student,Leo,"12,May,2004",testing testing
4,3581210,male,33,InvestmentBanking,Aquarius,"11,June,2004",thanks yahoos toolbar capture urls popupswhich...
5,3581210,male,33,InvestmentBanking,Aquarius,"10,June,2004",interesting conversation dad morning talking k...
6,3581210,male,33,InvestmentBanking,Aquarius,"10,June,2004",somehow cocacola way summing things well early...
7,3581210,male,33,InvestmentBanking,Aquarius,"10,June,2004",anything korea country extremes everything see...
8,3581210,male,33,InvestmentBanking,Aquarius,"10,June,2004",take read news article urllink joongang ilbo n...
9,3581210,male,33,InvestmentBanking,Aquarius,"09,June,2004",surf english news sites lot looking tidbits ko...
10,3581210,male,33,InvestmentBanking,Aquarius,"09,June,2004",ah korean languageit looks difficult first fig...
11,3581210,male,33,InvestmentBanking,Aquarius,"09,June,2004",click profile youll make notsostartling discov...
12,3581210,male,33,InvestmentBanking,Aquarius,"09,June,2004",last night pretty funmostly company kept recen...
13,3581210,male,33,InvestmentBanking,Aquarius,"09,June,2004",much different anything ive ever seen well hav...
14,3581210,male,33,InvestmentBanking,Aquarius,"09,June,2004",urllink superfantastic phonebox today great da...
15,3581210,male,33,InvestmentBanking,Aquarius,"09,June,2004",one thing love seoul mean korea generali happe...
16,3581210,male,33,InvestmentBanking,Aquarius,"09,June,2004",urllink wonderful ohgyupsal favorite pork rest...
17,3581210,male,33,InvestmentBanking,Aquarius,"18,June,2004",latest korean rumor mill made way coquitlam wi...
18,3581210,male,33,InvestmentBanking,Aquarius,"17,June,2004",well stand corrected yesterday blogged coquitl...
19,3581210,male,33,InvestmentBanking,Aquarius,"16,June,2004",ive vancouver days nowin coquitlam actually re...
20,3581210,male,33,InvestmentBanking,Aquarius,"15,June,2004",whenever see pregnant korean lady really feel ...
21,3581210,male,33,InvestmentBanking,Aquarius,"14,June,2004",wife posed strange question tonight apparently...
22,3581210,male,33,InvestmentBanking,Aquarius,"13,June,2004",readers know favorite airline singapore air sa...
23,3581210,male,33,InvestmentBanking,Aquarius,"23,June,2004",seoul last months thought wife kinda easy kid...
24,3581210,male,33,InvestmentBanking,Aquarius,"22,June,2004",may noticed new feature blogits blog email not...
25,3581210,male,33,InvestmentBanking,Aquarius,"20,June,2004",korea especially seoul pretty cool canada espe...
26,3581210,male,33,InvestmentBanking,Aquarius,"02,July,2004",seems everything smooth seoul concerning recen...
27,3581210,male,33,InvestmentBanking,Aquarius,"01,July,2004",may long bloggot lot thoughts going head last ...
28,3581210,male,33,InvestmentBanking,Aquarius,"01,July,2004",ive always thought seouls urllink subways real...
29,3581210,male,33,InvestmentBanking,Aquarius,"30,June,2004",big cities famous expensive places live others...
...,...,...,...,...,...,...,...
4970,1103575,female,17,indUnk,Scorpio,"06,July,2003",mm going rant timeclockswatches like says soci...
4971,1103575,female,17,indUnk,Scorpio,"06,July,2003",guess kind like already told ive fallen pieces...
4972,1103575,female,17,indUnk,Scorpio,"03,July,2003",shade red looks like blood doesnt matter doesn...
4973,1103575,female,17,indUnk,Scorpio,"03,July,2003",look teaching html well suppose halfway decent...
4974,1103575,female,17,indUnk,Scorpio,"03,July,2003",name rachel duh already knew rachel hebrew mea...
4975,1103575,female,17,indUnk,Scorpio,"02,July,2003",another depressing song dont know like suppose...
4976,1103575,female,17,indUnk,Scorpio,"01,July,2003",ive falling pieces past several months think i...
4977,1103575,female,17,indUnk,Scorpio,"31,August,2003",im suffocating lungs bursting hit would pop li...
4978,1103575,female,17,indUnk,Scorpio,"30,August,2003",peaches nectar gods mmmmmmmmm sometimes im lay...
4979,1103575,female,17,indUnk,Scorpio,"30,August,2003",ahhh need pillow scream oh book im reading guy...
4980,1103575,female,17,indUnk,Scorpio,"29,August,2003",young really young id say anywhere youll go b...
4981,1103575,female,17,indUnk,Scorpio,"29,August,2003",thats sama
4982,1103575,female,17,indUnk,Scorpio,"29,August,2003",
4983,1103575,female,17,indUnk,Scorpio,"29,August,2003",
4984,1103575,female,17,indUnk,Scorpio,"29,August,2003",one looks kinda cool squished like
4985,1103575,female,17,indUnk,Scorpio,"29,August,2003",yay uploading pics angelfire putting blog exce...
4986,1103575,female,17,indUnk,Scorpio,"29,August,2003",ok last time today promise im really really go...
4987,1103575,female,17,indUnk,Scorpio,"28,August,2003",oh forgot last night cantor practice consistan...
4988,1103575,female,17,indUnk,Scorpio,"28,August,2003",got new commenting host didnt like old one thi...
4989,1103575,female,17,indUnk,Scorpio,"28,August,2003",last night good night end story today interest...
4990,1103575,female,17,indUnk,Scorpio,"28,August,2003",sometimes swear song am matchbox twenty say co...
4991,1103575,female,17,indUnk,Scorpio,"28,August,2003",much sleeping know time know time used think m...
4992,1103575,female,17,indUnk,Scorpio,"28,August,2003",miserable failure incredibly irresponsible lat...
4993,1103575,female,17,indUnk,Scorpio,"27,August,2003",hey ive almost hits people
4994,1103575,female,17,indUnk,Scorpio,"27,August,2003",sylvia plath poem talking tulips sylvia plath ...
4995,1103575,female,17,indUnk,Scorpio,"27,August,2003",another one dreams last night except time leas...
4996,1103575,female,17,indUnk,Scorpio,"27,August,2003",mmm strawberry tea breakfast tomorrow think de...
4997,1103575,female,17,indUnk,Scorpio,"27,August,2003",yay new layout yeah know need get complicated ...
4998,1103575,female,17,indUnk,Scorpio,"26,August,2003",ok lied fed isnt playing friday night underdog...
4999,1103575,female,17,indUnk,Scorpio,"26,August,2003",well today went church talked music director t...

In [124]:
# 3) Merging labels together

df2 = df.assign(labels = df.gender.astype(str) + ', ' +
  df.age.astype(str) + ', ' + df.topic.astype(str) + ', ' +
  df.sign.astype(str))

df2['labels'] = [x for x in df2['labels'].str.split(',') if x]
df2['labels']

0                      [male,  15,  Student,  Leo]
1                      [male,  15,  Student,  Leo]
2                      [male,  15,  Student,  Leo]
3                      [male,  15,  Student,  Leo]
4       [male,  33,  InvestmentBanking,  Aquarius]
5       [male,  33,  InvestmentBanking,  Aquarius]
6       [male,  33,  InvestmentBanking,  Aquarius]
7       [male,  33,  InvestmentBanking,  Aquarius]
8       [male,  33,  InvestmentBanking,  Aquarius]
9       [male,  33,  InvestmentBanking,  Aquarius]
10      [male,  33,  InvestmentBanking,  Aquarius]
11      [male,  33,  InvestmentBanking,  Aquarius]
12      [male,  33,  InvestmentBanking,  Aquarius]
13      [male,  33,  InvestmentBanking,  Aquarius]
14      [male,  33,  InvestmentBanking,  Aquarius]
15      [male,  33,  InvestmentBanking,  Aquarius]
16      [male,  33,  InvestmentBanking,  Aquarius]
17      [male,  33,  InvestmentBanking,  Aquarius]
18      [male,  33,  InvestmentBanking,  Aquarius]
19      [male,  33,  InvestmentBanking,  Aquarius]
20      [male,  33,  InvestmentBanking,  Aquarius]
21      [male,  33,  InvestmentBanking,  Aquarius]
22      [male,  33,  InvestmentBanking,  Aquarius]
23      [male,  33,  InvestmentBanking,  Aquarius]
24      [male,  33,  InvestmentBanking,  Aquarius]
25      [male,  33,  InvestmentBanking,  Aquarius]
26      [male,  33,  InvestmentBanking,  Aquarius]
27      [male,  33,  InvestmentBanking,  Aquarius]
28      [male,  33,  InvestmentBanking,  Aquarius]
29      [male,  33,  InvestmentBanking,  Aquarius]
                           ...
4970              [female,  17,  indUnk,  Scorpio]
4971              [female,  17,  indUnk,  Scorpio]
4972              [female,  17,  indUnk,  Scorpio]
4973              [female,  17,  indUnk,  Scorpio]
4974              [female,  17,  indUnk,  Scorpio]
4975              [female,  17,  indUnk,  Scorpio]
4976              [female,  17,  indUnk,  Scorpio]
4977              [female,  17,  indUnk,  Scorpio]
4978              [female,  17,  indUnk,  Scorpio]
4979              [female,  17,  indUnk,  Scorpio]
4980              [female,  17,  indUnk,  Scorpio]
4981              [female,  17,  indUnk,  Scorpio]
4982              [female,  17,  indUnk,  Scorpio]
4983              [female,  17,  indUnk,  Scorpio]
4984              [female,  17,  indUnk,  Scorpio]
4985              [female,  17,  indUnk,  Scorpio]
4986              [female,  17,  indUnk,  Scorpio]
4987              [female,  17,  indUnk,  Scorpio]
4988              [female,  17,  indUnk,  Scorpio]
4989              [female,  17,  indUnk,  Scorpio]
4990              [female,  17,  indUnk,  Scorpio]
4991              [female,  17,  indUnk,  Scorpio]
4992              [female,  17,  indUnk,  Scorpio]
4993              [female,  17,  indUnk,  Scorpio]
4994              [female,  17,  indUnk,  Scorpio]
4995              [female,  17,  indUnk,  Scorpio]
4996              [female,  17,  indUnk,  Scorpio]
4997              [female,  17,  indUnk,  Scorpio]
4998              [female,  17,  indUnk,  Scorpio]
4999              [female,  17,  indUnk,  Scorpio]
Name: labels, Length: 5000, dtype: object

In [96]:
# consider only text and labels for model building

df2.drop(columns=['id','gender','age','topic','sign','date'])

,text,labels
0,info found pages mb pdf files wait untill te...,"[male, 15, Student, Leo]"
1,team members drewes van der laag urllink mail ...,"[male, 15, Student, Leo]"
2,het kader van kernfusie op aarde maak je eigen...,"[male, 15, Student, Leo]"
3,testing testing,"[male, 15, Student, Leo]"
4,thanks yahoos toolbar capture urls popupswhich...,"[male, 33, InvestmentBanking, Aquarius]"
5,interesting conversation dad morning talking k...,"[male, 33, InvestmentBanking, Aquarius]"
6,somehow cocacola way summing things well early...,"[male, 33, InvestmentBanking, Aquarius]"
7,anything korea country extremes everything see...,"[male, 33, InvestmentBanking, Aquarius]"
8,take read news article urllink joongang ilbo n...,"[male, 33, InvestmentBanking, Aquarius]"
9,surf english news sites lot looking tidbits ko...,"[male, 33, InvestmentBanking, Aquarius]"
10,ah korean languageit looks difficult first fig...,"[male, 33, InvestmentBanking, Aquarius]"
11,click profile youll make notsostartling discov...,"[male, 33, InvestmentBanking, Aquarius]"
12,last night pretty funmostly company kept recen...,"[male, 33, InvestmentBanking, Aquarius]"
13,much different anything ive ever seen well hav...,"[male, 33, InvestmentBanking, Aquarius]"
14,urllink superfantastic phonebox today great da...,"[male, 33, InvestmentBanking, Aquarius]"
15,one thing love seoul mean korea generali happe...,"[male, 33, InvestmentBanking, Aquarius]"
16,urllink wonderful ohgyupsal favorite pork rest...,"[male, 33, InvestmentBanking, Aquarius]"
17,latest korean rumor mill made way coquitlam wi...,"[male, 33, InvestmentBanking, Aquarius]"
18,well stand corrected yesterday blogged coquitl...,"[male, 33, InvestmentBanking, Aquarius]"
19,ive vancouver days nowin coquitlam actually re...,"[male, 33, InvestmentBanking, Aquarius]"
20,whenever see pregnant korean lady really feel ...,"[male, 33, InvestmentBanking, Aquarius]"
21,wife posed strange question tonight apparently...,"[male, 33, InvestmentBanking, Aquarius]"
22,readers know favorite airline singapore air sa...,"[male, 33, InvestmentBanking, Aquarius]"
23,seoul last months thought wife kinda easy kid...,"[male, 33, InvestmentBanking, Aquarius]"
24,may noticed new feature blogits blog email not...,"[male, 33, InvestmentBanking, Aquarius]"
25,korea especially seoul pretty cool canada espe...,"[male, 33, InvestmentBanking, Aquarius]"
26,seems everything smooth seoul concerning recen...,"[male, 33, InvestmentBanking, Aquarius]"
27,may long bloggot lot thoughts going head last ...,"[male, 33, InvestmentBanking, Aquarius]"
28,ive always thought seouls urllink subways real...,"[male, 33, InvestmentBanking, Aquarius]"
29,big cities famous expensive places live others...,"[male, 33, InvestmentBanking, Aquarius]"
...,...,...
4970,mm going rant timeclockswatches like says soci...,"[female, 17, indUnk, Scorpio]"
4971,guess kind like already told ive fallen pieces...,"[female, 17, indUnk, Scorpio]"
4972,shade red looks like blood doesnt matter doesn...,"[female, 17, indUnk, Scorpio]"
4973,look teaching html well suppose halfway decent...,"[female, 17, indUnk, Scorpio]"
4974,name rachel duh already knew rachel hebrew mea...,"[female, 17, indUnk, Scorpio]"
4975,another depressing song dont know like suppose...,"[female, 17, indUnk, Scorpio]"
4976,ive falling pieces past several months think i...,"[female, 17, indUnk, Scorpio]"
4977,im suffocating lungs bursting hit would pop li...,"[female, 17, indUnk, Scorpio]"
4978,peaches nectar gods mmmmmmmmm sometimes im lay...,"[female, 17, indUnk, Scorpio]"
4979,ahhh need pillow scream oh book im reading guy...,"[female, 17, indUnk, Scorpio]"
4980,young really young id say anywhere youll go b...,"[female, 17, indUnk, Scorpio]"
4981,thats sama,"[female, 17, indUnk, Scorpio]"
4982,,"[female, 17, indUnk, Scorpio]"
4983,,"[female, 17, indUnk, Scorpio]"
4984,one looks kinda cool squished like,"[female, 17, indUnk, Scorpio]"
4985,yay uploading pics angelfire putting blog exce...,"[female, 17, indUnk, Scorpio]"
4986,ok last time today promise im really really go...,"[female, 17, indUnk, Scorpio]"
4987,oh forgot last night cantor practice consistan...,"[female, 17, indUnk, Scorpio]"
4988,got new commenting host didnt like old one thi...,"[female, 17, indUnk, Scorpio]"
4989,last night good night end story today interest...,"[female, 17, indUnk, Scorpio]"
4990,sometimes swear song am matchbox twenty say co...,"[female, 17, indUnk, Scorpio]"
4991,much sleeping know time know time used think m...,"[female, 17, indUnk, Scorpio]"
4992,miserable failure incredibly irresponsible lat...,"[female, 17, indUnk, Scorpio]"
4993,hey ive almost hits people,"[female, 17, indUnk, Scorpio]"
4994,sylvia plath poem talking tulips sylvia plath ...,"[female, 17, indUnk, Scorpio]"
4995,another one dreams last night except time leas...,"[female, 17, indUnk, Scorpio]"
4996,mmm strawberry tea breakfast tomorrow think de...,"[female, 17, indUnk, Scorpio]"
4997,yay new layout yeah know need get complicated ...,"[female, 17, indUnk, Scorpio]"
4998,ok lied fed isnt playing friday night underdog...,"[female, 17, indUnk, Scorpio]"
4999,well today went church talked music director t...,"[female, 17, indUnk, Scorpio]"

In [97]:
# 4) Separate features and labels for training and testing

X= df2['text']
y=df2['labels']

# split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=2)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(3500,)
(1500,)
(3500,)
(1500,)

In [98]:
y_train

2416              [male,  35,  Technology,  Aries]
2417              [male,  35,  Technology,  Aries]
2513              [male,  35,  Technology,  Aries]
1698              [male,  35,  Technology,  Aries]
3322              [male,  35,  Technology,  Aries]
4133          [female,  34,  indUnk,  Sagittarius]
3116              [male,  35,  Technology,  Aries]
614              [male,  24,  Engineering,  Libra]
2342              [male,  35,  Technology,  Aries]
1161               [female,  16,  indUnk,  Taurus]
827            [male,  17,  Student,  Sagittarius]
1992              [male,  35,  Technology,  Aries]
4664                 [female,  25,  Student,  Leo]
4043                  [female,  16,  indUnk,  Leo]
2842              [male,  35,  Technology,  Aries]
290               [female,  24,  indUnk,  Scorpio]
226               [male,  15,  Student,  Aquarius]
4899              [female,  17,  indUnk,  Scorpio]
741     [male,  41,  Communications-Media,  Libra]
4523          [female,  34,  indUnk,  Sagittarius]
3753                 [female,  17,  Student,  Leo]
1559              [male,  35,  Technology,  Aries]
961                [male,  14,  Student,  Scorpio]
3018              [male,  35,  Technology,  Aries]
2718              [male,  35,  Technology,  Aries]
2187              [male,  35,  Technology,  Aries]
75                  [female,  14,  indUnk,  Aries]
3767                 [female,  17,  Student,  Leo]
411               [female,  24,  indUnk,  Scorpio]
401               [female,  24,  indUnk,  Scorpio]
                           ...
3122              [male,  35,  Technology,  Aries]
3310              [male,  35,  Technology,  Aries]
1588              [male,  35,  Technology,  Aries]
3664              [male,  35,  Technology,  Aries]
2498              [male,  35,  Technology,  Aries]
31      [male,  33,  InvestmentBanking,  Aquarius]
3283              [male,  35,  Technology,  Aries]
1375              [female,  25,  Student,  Taurus]
1326                [female,  15,  indUnk,  Aries]
3780                 [female,  17,  Student,  Leo]
1349              [female,  25,  Student,  Taurus]
255                     [male,  26,  indUnk,  Leo]
3642              [male,  35,  Technology,  Aries]
3622              [male,  35,  Technology,  Aries]
4147          [female,  34,  indUnk,  Sagittarius]
4971              [female,  17,  indUnk,  Scorpio]
2727              [male,  35,  Technology,  Aries]
3700    [male,  39,  Communications-Media,  Libra]
124                [female,  17,  Student,  Aries]
2778              [male,  35,  Technology,  Aries]
2879              [male,  35,  Technology,  Aries]
2773              [male,  35,  Technology,  Aries]
2635              [male,  35,  Technology,  Aries]
433               [female,  24,  indUnk,  Scorpio]
4770        [male,  33,  Technology,  Sagittarius]
3335              [male,  35,  Technology,  Aries]
1099               [female,  15,  Student,  Libra]
2514              [male,  35,  Technology,  Aries]
3606              [male,  35,  Technology,  Aries]
2575              [male,  35,  Technology,  Aries]
Name: labels, Length: 3500, dtype: object

In [28]:
X_test

3566    well liberals officially confronted nader  run...
4252    feeling quite inspired nothing like breaking n...
1918                            hope feel better soon ben
4111    burned tongue oatmeal morning started thinking...
1471      pm miriam maddux okay okay something wry int...
929     today school huge mess yes pe realised could a...
1916    mir opinion yes one sacrifice ones mood happin...
3995    time  said earlier company work urllink kmg mo...
1130    woo today fun mum woke like  like hey going be...
1723                                     testing new edit
2384    still havent figure whether harmony psychotic ...
4200
88      ever felt horrible like million knifes stabbin...
1778                  like cheese cant cheese anymore sad
1428    hey buckle swashes someplace else pal family f...
317                 argh  arghhhhhhh time look one either
2782                                          jsflkejfldk
2656    urllink urllink weeks episode road glory check...
966     yes told animal titles would comments teams sp...
2079                                      love strong bad
35      busy last couple weeks im way back seoul today...
671     officially borderline alcoholic woke morning  ...
2391    question lets say someone something unintentio...
1635    batmanthe musical dont know whether horrified ...
3774    ill never see againnever wear againi miss alre...
1575                                          thanks neal
2224                                         go babies go
563     nbspnbspnbspnbsp give sense humor lord story p...
938     amazing races sports injury ethan alter amazin...
1420                     testingtaptaptap hey thing hello
                              ...
1354      urllink machiko marcus happy couplenbsp urllink
3388    john doesnt pass well thought ad regarding pre...
2691    fallen prey angies quizzes result outlet dont ...
3483    despite president bushs pledge homosexuals oug...
1041    well guess confusedand sad good thing im going...
4857    hmm reading jen feeling kinda empty moment get...
1187    everybody shake time free amongst momma told d...
1966    know think infuriates whats asks zee bear peop...
4966    tell im bored funny urllink barbecue anyone ne...
1638                            many chickens one rooster
261     kind continuation previos story line blog job ...
2358    anyone besides see friend ben cable access las...
650     day rises anew contemplate efficacy rapport hu...
617     really need something looks huh well im lazy s...
2569    im sure angie appreciates importance game post...
1136    already guess time flys youre fun yesterday mu...
1896        funny angie dr take care cats chuckle tee hee
3665    wow war terror means compatriots urllink longe...
2714           official stuff urllink check giddy monkeys
729     driving work saw sky tv van parked side road n...
998     hey one many things expression zone hope updat...
3209             need picture nick perhaps one lovely eva
2703                          stamping licking glee worry
3575    read another website richard biggs dr franklin...
1775                                      oh nothing give
570     well independance day upon us wish everyone fu...
4853    heather taped youre going pee pants think seas...
768     error page got tania go urllink google search ...
2085    wtf see karl talking last night instead silly ...
4836                    urllink swimming darknbsp urllink
Name: text, Length: 1500, dtype: object

In [99]:
# 5) Vectorize the features

# instantiate the vectorizer
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer(ngram_range=(1, 2))

# Vectorize training and test set
X_train_dtm = vect.fit_transform(X_train)
X_test_dtm = vect.transform(X_test)
X_train_dtm
X_test_dtm

<1500x246900 sparse matrix of type '<class 'numpy.int64'>'
	with 111763 stored elements in Compressed Sparse Row format>

In [16]:
# examine the vocabulary and document-term matrix together for train set
pd.DataFrame(X_train_dtm.toarray(), columns=vect.get_feature_names())

,__,__ ___,___,___ ___,___ fools,___ foolsnbsp,____,____ position,___accomplishments,___accomplishments provide,...,제주도jejudo also,초복,초복 chobok,치과,치과 chigwa,푸하하하,한방삼계탕,한방삼계탕 hanbangsamgyetang,회식,회식 hwishik
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,1,1,0,0
671,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
672,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
673,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
674,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
675,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
676,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
677,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
678,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
679,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
680,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
681,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
682,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
683,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
684,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
685,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
686,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
687,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
688,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
689,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
690,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
691,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
692,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
693,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
694,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
695,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
696,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
697,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
698,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
699,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [328]:
# examine the vocabulary and document-term matrix together for test set
pd.DataFrame(X_test_dtm.toarray(), columns=vect.get_feature_names())

,__,__ ___,___,___ ___,___ fools,___ foolsnbsp,____,____ position,___accomplishments,___accomplishments provide,...,제주도jejudo also,초복,초복 chobok,치과,치과 chigwa,푸하하하,한방삼계탕,한방삼계탕 hanbangsamgyetang,회식,회식 hwishik
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
221,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
222,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
223,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
224,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
225,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
226,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
227,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
228,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
229,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
230,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
231,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
232,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
233,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
234,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
235,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
236,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
237,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
238,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
239,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
240,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
241,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
242,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
243,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
244,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
245,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
246,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
247,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
248,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
249,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [494]:
# 6)  Count of each distnct label value and store in a dictionary

vec = CountVectorizer(tokenizer=lambda x: [i.strip() for i in x.split(',')], lowercase=False)
counts = vec.fit_transform(df2['labels'])
dict(zip(vec.get_feature_names(), counts.sum(axis=0).tolist()[0]))

{'14': 170,
 '15': 339,
 '16': 67,
 '17': 331,
 '23': 137,
 '24': 353,
 '25': 268,
 '26': 96,
 '27': 86,
 '33': 101,
 '34': 540,
 '35': 2307,
 '36': 60,
 '37': 19,
 '39': 79,
 '41': 14,
 '42': 9,
 '44': 3,
 '45': 14,
 '46': 7,
 'Accounting': 2,
 'Aquarius': 329,
 'Aries': 2483,
 'Arts': 31,
 'Automotive': 14,
 'Banking': 16,
 'BusinessServices': 87,
 'Cancer': 94,
 'Capricorn': 84,
 'Communications-Media': 61,
 'Consulting': 16,
 'Education': 118,
 'Engineering': 119,
 'Gemini': 86,
 'Internet': 20,
 'InvestmentBanking': 70,
 'Law': 3,
 'Leo': 190,
 'Libra': 414,
 'Museums-Libraries': 2,
 'Non-Profit': 47,
 'Pisces': 67,
 'Religion': 4,
 'Sagittarius': 704,
 'Science': 33,
 'Scorpio': 408,
 'Sports-Recreation': 75,
 'Student': 569,
 'Taurus': 100,
 'Technology': 2332,
 'Virgo': 41,
 'female': 1706,
 'indUnk': 1381,
 'male': 3294}

In [100]:
# 7) MultilabelBinarizer

from sklearn.preprocessing import MultiLabelBinarizer

multilabel_binarizer = MultiLabelBinarizer()
multilabel_binarizer.fit(y_train)

# transform train label
y_train = multilabel_binarizer.transform(y_train)
# transform test label
y_test = multilabel_binarizer.transform(y_test)

In [101]:
multilabel_binarizer.inverse_transform(y_train)

[(' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 24', ' Engineering', ' Libra', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 16', ' Taurus', ' indUnk', 'female'),
 (' 17', ' Sagittarius', ' Student', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 25', ' Leo', ' Student', 'female'),
 (' 16', ' Leo', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 15', ' Aquarius', ' Student', 'male'),
 (' 17', ' Scorpio', ' indUnk', 'female'),
 (' 41', ' Communications-Media', ' Libra', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 17', ' Leo', ' Student', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 14', ' Scorpio', ' Student', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 14', ' Aries', ' indUnk', 'female'),
 (' 17', ' Leo', ' Student', 'female'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 25', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 16', ' Libra', ' Student', 'female'),
 (' 25', ' Aries', ' Internet', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 36', ' Pisces', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', ' Libra', ' Student', 'female'),
 (' 23', ' Sagittarius', ' indUnk', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 17', ' Sagittarius', ' Student', 'male'),
 (' 45', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', ' Leo', ' Student', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 16', ' Taurus', ' indUnk', 'female'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 24', ' Capricorn', ' Religion', 'female'),
 (' 15', ' Leo', ' Student', 'female'),
 (' 25', ' Libra', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 16', ' Taurus', ' indUnk', 'female'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 36', ' Pisces', ' indUnk', 'female'),
 (' 27', ' Aquarius', ' Education', 'female'),
 (' 15', ' Aquarius', ' Student', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 23', ' Student', ' Taurus', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 23', ' Libra', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 36', ' Pisces', ' indUnk', 'female'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 17', ' Scorpio', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 16', ' Taurus', ' indUnk', 'female'),
 (' 26', ' Gemini', ' indUnk', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 14', ' Leo', ' Student', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 15', ' Aquarius', ' Student', 'female'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 14', ' Pisces', ' Student', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 33', ' Aquarius', ' InvestmentBanking', 'male'),
 (' 17', ' Capricorn', ' Sports-Recreation', 'male'),
 (' 17', ' Scorpio', ' Student', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 25', ' Aries', ' Internet', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 17', ' Leo', ' Student', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', ' Gemini', ' Student', 'female'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 25', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 39', ' Education', ' Virgo', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 24', ' Engineering', ' Libra', 'male'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 14', ' Aries', ' indUnk', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 17', ' Scorpio', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 14', ' Leo', ' indUnk', 'female'),
 (' 33', ' Aquarius', ' InvestmentBanking', 'male'),
 (' 24', ' Aries', ' indUnk', 'female'),
 (' 14', ' Scorpio', ' indUnk', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 26', ' Gemini', ' indUnk', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 17', ' Sagittarius', ' Student', 'male'),
 (' 17', ' Aries', ' Student', 'female'),
 (' 14', ' Scorpio', ' indUnk', 'male'),
 (' 14', ' Scorpio', ' Student', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 39', ' Communications-Media', ' Libra', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 14', ' Aries', ' indUnk', 'female'),
 (' 15', ' Libra', ' Student', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', ' Aquarius', ' Student', 'female'),
 (' 25', ' Cancer', ' Non-Profit', 'male'),
 (' 17', ' Capricorn', ' Sports-Recreation', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 25', ' Student', ' Taurus', 'female'),
 (' 17', ' Leo', ' Student', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 39', ' Education', ' Virgo', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 15', ' Leo', ' Student', 'female'),
 (' 25', ' Leo', ' Student', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 14', ' Aries', ' indUnk', 'female'),
 (' 24', ' Engineering', ' Libra', 'male'),
 (' 17', ' Scorpio', ' indUnk', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 23', ' Taurus', ' indUnk', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', ' Libra', ' Student', 'female'),
 (' 23', ' Sagittarius', ' indUnk', 'male'),
 (' 25', ' Taurus', ' indUnk', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 26', ' Gemini', ' indUnk', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 25', ' Cancer', ' Non-Profit', 'male'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 39', ' Communications-Media', ' Libra', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 24', ' Engineering', ' Libra', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 45', ' Sagittarius', ' indUnk', 'female'),
 (' 17', ' Aquarius', ' indUnk', 'male'),
 (' 36', ' Gemini', ' Student', 'female'),
 (' 36', ' Pisces', ' indUnk', 'female'),
 (' 17', ' Capricorn', ' Sports-Recreation', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 14', ' Pisces', ' Student', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 16', ' Libra', ' Student', 'female'),
 (' 25', ' Libra', ' indUnk', 'female'),
 (' 24', ' Engineering', ' Libra', 'male'),
 (' 26', ' Leo', ' indUnk', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 14', ' Scorpio', ' Student', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 14', ' Leo', ' Student', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 14', ' Leo', ' Student', 'male'),
 (' 33', ' Aquarius', ' Banking', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 36', ' Pisces', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 25', ' Aries', ' BusinessServices', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 27', ' Aquarius', ' Education', 'female'),
 (' 24', ' Engineering', ' Libra', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 39', ' Communications-Media', ' Libra', 'male'),
 (' 23', ' Sagittarius', ' indUnk', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 26', ' Libra', ' indUnk', 'female'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 46', ' Consulting', ' Gemini', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 24', ' Engineering', ' Libra', 'male'),
 (' 15', ' Libra', ' Student', 'female'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 27', ' Aquarius', ' Education', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 23', ' Sagittarius', ' indUnk', 'male'),
 (' 24', ' Engineering', ' Libra', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', ' Aquarius', ' Student', 'female'),
 (' 27', ' Aquarius', ' Education', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 39', ' Communications-Media', ' Libra', 'male'),
 (' 14', ' Leo', ' Student', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 24', ' Engineering', ' Libra', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 17', ' Aries', ' Student', 'female'),
 (' 25', ' Aries', ' BusinessServices', 'female'),
 (' 15', ' Libra', ' Student', 'female'),
 (' 27', ' Aquarius', ' Education', 'female'),
 (' 25', ' Aries', ' Internet', 'male'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 33', ' Aquarius', ' Banking', 'female'),
 (' 25', ' Student', ' Taurus', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', ' Aquarius', ' Student', 'female'),
 (' 17', ' Scorpio', ' indUnk', 'female'),
 (' 15', ' Libra', ' Student', 'female'),
 (' 23', ' Aquarius', ' indUnk', 'female'),
 (' 27', ' Aquarius', ' Education', 'female'),
 (' 17', ' Aries', ' Student', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 24', ' Engineering', ' Libra', 'male'),
 (' 25', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 25', ' Aries', ' Internet', 'male'),
 (' 23', ' Student', ' Taurus', 'female'),
 (' 15', ' Sagittarius', ' Student', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', ' Libra', ' Student', 'female'),
 (' 26', ' Gemini', ' indUnk', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 24', ' Aries', ' indUnk', 'female'),
 (' 27', ' Aquarius', ' Education', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 25', ' Capricorn', ' Non-Profit', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 25', ' Student', ' Taurus', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 25', ' BusinessServices', ' Sagittarius', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 26', ' Leo', ' indUnk', 'male'),
 (' 14', ' Scorpio', ' Student', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 17', ' Leo', ' Student', 'female'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 27', ' Aquarius', ' Education', 'female'),
 (' 17', ' Capricorn', ' Sports-Recreation', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 17', ' Capricorn', ' Sports-Recreation', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', ' Aquarius', ' Student', 'female'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 23', ' Aquarius', ' Automotive', 'female'),
 (' 17', ' Aquarius', ' indUnk', 'male'),
 (' 15', ' Libra', ' Student', 'female'),
 (' 17', ' Sagittarius', ' Student', 'male'),
 (' 26', ' Leo', ' indUnk', 'male'),
 (' 25', ' Cancer', ' Non-Profit', 'male'),
 (' 25', ' Aries', ' Arts', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 15', ' Aquarius', ' Student', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 15', ' Libra', ' Science', 'male'),
 (' 17', ' Capricorn', ' Sports-Recreation', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 17', ' Gemini', ' Student', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 36', ' Pisces', ' indUnk', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 16', ' Taurus', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 15', ' Aquarius', ' Student', 'female'),
 (' 17', ' Aries', ' Student', 'female'),
 (' 24', ' Engineering', ' Libra', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 25', ' Aries', ' Technology', 'male'),
 (' 36', ' Pisces', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 24', ' Engineering', ' Libra', 'male'),
 (' 33', ' Aquarius', ' InvestmentBanking', 'male'),
 (' 15', ' Libra', ' Student', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 25', ' Aries', ' BusinessServices', 'female'),
 (' 23', ' Sagittarius', ' Student', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 17', ' Scorpio', ' indUnk', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 25', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 24', ' Aries', ' indUnk', 'female'),
 (' 15', ' Aquarius', ' Student', 'female'),
 (' 39', ' Communications-Media', ' Libra', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 16', ' Taurus', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', ' Libra', ' Student', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 25', ' Cancer', ' Non-Profit', 'male'),
 (' 23', ' Sagittarius', ' indUnk', 'male'),
 (' 37', ' Aquarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 17', ' Scorpio', ' indUnk', 'female'),
 (' 24', ' Engineering', ' Libra', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 27', ' Aquarius', ' Education', 'female'),
 (' 17', ' Sagittarius', ' Student', 'male'),
 (' 15', ' Libra', ' Student', 'female'),
 (' 39', ' Education', ' Virgo', 'male'),
 (' 17', ' Sagittarius', ' Student', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 17', ' Scorpio', ' indUnk', 'female'),
 (' 25', ' Libra', ' indUnk', 'female'),
 (' 17', ' Scorpio', ' indUnk', 'female'),
 (' 33', ' Aquarius', ' InvestmentBanking', 'male'),
 (' 26', ' Gemini', ' indUnk', 'male'),

In [102]:
#8) OnevsRest on Logistic Regression for Model building

from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn import metrics

lr = LogisticRegression()
clf = OneVsRestClassifier(lr)

# fit model on train data
clf.fit(X_train_dtm, y_train)

# predict for the test set
y_pred = clf.predict(X_test_dtm)

C:\Users\sriram.kannan\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [632]:
y_pred[0]

array([1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1])

In [103]:
# Accuracy for the model
print(metrics.accuracy_score(y_test, y_pred))

0.5213333333333333

In [104]:
# 9) Classification Report - F1 Score, Avg Precision and Avg Recall
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(metrics.accuracy_score(y_test, y_pred))
print(classification_report(y_test,y_pred))

0.5213333333333333
              precision    recall  f1-score   support

           0       0.67      0.10      0.18        59
           1       0.79      0.32      0.46        96
           2       0.00      0.00      0.00        25
           3       0.90      0.26      0.40       100
           4       0.00      0.00      0.00        38
           5       0.92      0.34      0.50       106
           6       0.33      0.06      0.10        69
           7       0.00      0.00      0.00        35
           8       1.00      0.03      0.06        30
           9       1.00      0.32      0.49        31
          10       0.95      0.75      0.84       165
          11       0.83      0.91      0.86       683
          12       0.00      0.00      0.00        15
          13       0.00      0.00      0.00         8
          14       0.00      0.00      0.00        26
          15       0.00      0.00      0.00         8
          16       0.00      0.00      0.00         2
          17       0.00      0.00      0.00         0
          18       0.00      0.00      0.00         3
          19       0.00      0.00      0.00         1
          20       0.00      0.00      0.00         1
          21       0.71      0.20      0.31        99
          22       0.82      0.89      0.85       740
          23       0.00      0.00      0.00         9
          24       0.00      0.00      0.00         6
          25       0.00      0.00      0.00         5
          26       0.88      0.24      0.38        29
          27       0.71      0.22      0.33        23
          28       1.00      0.29      0.45        24
          29       0.00      0.00      0.00        23
          30       0.00      0.00      0.00         3
          31       1.00      0.05      0.09        41
          32       1.00      0.23      0.38        39
          33       0.00      0.00      0.00        20
          34       0.00      0.00      0.00         5
          35       1.00      0.33      0.50        21
          36       0.00      0.00      0.00         1
          37       1.00      0.08      0.14        66
          38       0.80      0.34      0.48       131
          39       0.00      0.00      0.00         1
          40       0.00      0.00      0.00         7
          41       0.00      0.00      0.00        16
          42       0.00      0.00      0.00         1
          43       0.91      0.60      0.72       214
          44       0.00      0.00      0.00         9
          45       0.86      0.15      0.25       129
          46       1.00      0.32      0.48        22
          47       0.81      0.27      0.41       174
          48       0.00      0.00      0.00        24
          49       0.83      0.91      0.87       687
          50       0.00      0.00      0.00        14
          51       0.76      0.55      0.64       416
          52       0.85      0.67      0.75       526
          53       0.84      0.94      0.89       974

   micro avg       0.83      0.66      0.73      6000
   macro avg       0.43      0.19      0.24      6000
weighted avg       0.79      0.66      0.68      6000
 samples avg       0.80      0.66      0.69      6000

C:\Users\sriram.kannan\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sriram.kannan\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)

In [105]:
# 10) True and Predicted label for a few samples

for i in range(5): 
    print("Actual=%s, Predicted=%s" % (y_test[i],clf.predict(X_test_dtm[i])))

Actual=[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1], Predicted=[[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1]]
Actual=[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0], Predicted=[[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0]]
Actual=[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1], Predicted=[[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1]]
Actual=[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0], Predicted=[[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0]]
Actual=[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1], Predicted=[[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1]]

In [113]:
multilabel_binarizer.inverse_transform(y_pred)

[(' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Scorpio', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' indUnk', 'female'),
 (' Libra', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 14', ' Scorpio', ' Student', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('female',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' indUnk', 'male'),
 (' 14', ' Scorpio', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', ' Libra', ' Student', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', ' Libra', ' Student', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' indUnk', 'female'),
 ('female',),
 (' Libra', ' indUnk', 'female'),
 (' 17', ' Student', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' indUnk', 'male'),
 (' 17', ' Student', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Libra', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Libra', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Aries', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Student', 'female'),
 (' indUnk', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 25', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' indUnk', 'male'),
 ('female',),
 (' 17', ' Libra', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' indUnk', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' indUnk', 'male'),
 (' 24', ' Libra', 'female'),
 (' 24', ' 25', ' Scorpio', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 14', ' Aquarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 17', ' Student', 'female'),
 (' Aries', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', ' Libra', ' Student', 'female'),
 ('female',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Aries', 'male'),
 ('male',),
 (' 17', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 17', ' Sagittarius', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('female',),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 35', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 45', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Aries', 'male'),
 (' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', ' indUnk', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 24', 'male'),
 ('male',),
 (' 24', ' indUnk', 'female'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('female',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' indUnk', 'female'),
 (' Libra', ' Student', 'female'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', ' Libra', ' Student', 'female'),
 (' 24', ' BusinessServices', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Aquarius', ' indUnk', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 ('male',),
 (' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Student', 'female'),
 (' 33', ' Aquarius', ' InvestmentBanking', 'male'),
 (' 24', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 ('female',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', 'female'),
 (' 25', ' Sagittarius', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 25', 'female'),
 (' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' indUnk', 'female'),
 (' Aries', ' Technology', 'male'),
 ('male',),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' Aries', 'male'),
 (' Libra', ' indUnk', 'female'),
 ('female',),
 (' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Libra', ' indUnk', 'male'),
 (' 27', ' Aquarius', ' Education', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Aries', 'male'),
 (' Aries', 'male'),
 (' 15', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('female',),
 ('male',),
 (' Engineering', ' Libra', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' indUnk', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('female',),
 ('female',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', 'male'),
 (' Student', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Aries', 'female'),
 (' 35', ' Aries', 'male'),
 ('female',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 24', ' Aries', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' indUnk', 'male'),
 (' Aries', ' Technology', 'male'),
 (' Aries', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Libra', 'male'),
 (' Aries', 'male'),
 (' Libra', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 14', ' Scorpio', ' indUnk', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' Libra', ' Student', 'female'),
 (' indUnk', 'female'),
 ('male',),
 (' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', ' Libra', ' Student', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' indUnk', 'male'),
 ('female',),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' Student', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Aquarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 ('female',),
 (' Libra', 'male'),
 ('female',),
 (' 35', ' Aries', ' Technology', 'male'),
 ('female',),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Aries', 'male'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 24', ' Engineering', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', ' Libra', ' Student', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 24', ' Engineering', ' Libra', 'male'),
 ('male',),
 ('female',),
 (' Libra', 'male'),
 ('female',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('female',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 ('male',),
 ('female',),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Aries', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' indUnk', 'female'),
 ('male',),
 ('female',),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 ('female',),
 (' indUnk', 'female'),
 (' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('female',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 ('male',),
 (' 33', ' Aquarius', ' InvestmentBanking', 'male'),
 (' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 15', ' Student', 'female'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Technology', 'male'),
 (' Aries', 'male'),
 ('male',),
 (' 35', ' Aries', ' Libra', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('female',),
 (' 35', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Aquarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', ' Leo', ' Student', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Libra', ' indUnk', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', 'male'),
 ('male',),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 24', ' Scorpio', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', ' Libra', ' Student', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Aries', ' Technology', 'male'),
 (' Aries', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Engineering', ' Libra', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' Aquarius', ' indUnk', 'female'),
 (' Student', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', ' indUnk', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Aries', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 ('female',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' Aries', ' Technology', 'male'),
 (' 15', ' Aquarius', ' Student', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Aries', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' indUnk', 'female'),
 (' Libra', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 17', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('female',),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' Aries', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', ' 17', ' Student', 'female'),
 ('female',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 34', ' indUnk', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' Libra', 'male'),
 (' Student', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', ' 17', ' indUnk', 'female'),
 ('male',),
 ('male',),
 ('female',),
 (' 25', 'male'),
 ('male',),
 (' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Aries', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 25', ' Student', 'female'),
 ('male',),
 (' 15', ' Student', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' Aries', 'male'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' indUnk', 'female'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 ('male',),
 (' 35', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 15', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 34', ' Sagittarius', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' Aries', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 (' 25', ' BusinessServices', ' Sagittarius', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 ('male',),
 ('female',),
 (' 35', ' Aries', ' Technology', 'male'),
 (' indUnk', 'female'),
 (' indUnk', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' 35', ' Aries', ' Technology', 'male'),
 (' indUnk', 'male'),
 (' 24', ' indUnk', 'female'),
 (' 35', ' Aries', ' Technology', 'male'),

In [123]:
# 10) Actual vs Predict for sample 5 records of label column

for i in range(5): 
    print("Actual=%s, '\n'Predicted=%s" '\n'% (multilabel_binarizer.inverse_transform(y_test)[i],multilabel_binarizer.inverse_transform(y_pred)[i]))

Actual=(' 35', ' Aries', ' Technology', 'male'), '
'Predicted=(' 35', ' Aries', ' Technology', 'male')

Actual=(' 34', ' Sagittarius', ' indUnk', 'female'), '
'Predicted=(' 34', ' Sagittarius', ' indUnk', 'female')

Actual=(' 35', ' Aries', ' Technology', 'male'), '
'Predicted=(' 35', ' Aries', ' Technology', 'male')

Actual=(' 34', ' Sagittarius', ' indUnk', 'female'), '
'Predicted=(' 34', ' Sagittarius', ' indUnk', 'female')

Actual=(' 35', ' Aries', ' Technology', 'male'), '
'Predicted=(' 35', ' Aries', ' Technology', 'male')